USE employeesDB;
INSERT INTO department (`name`) VALUES ("MI6");
INSERT INTO department (`name`) VALUES ("Villan");
INSERT INTO department (`name`) VALUES ("Heroin");
INSERT INTO role (title, salary, department_id) VALUES ("Handler", 250000, 1);
INSERT INTO role (title, salary, department_id) VALUES ("Agent", 500000, 2);
INSERT INTO role (title, salary, department_id) VALUES ("Heroin Main", 200000, 3);
INSERT INTO role (title, salary, department_id) VALUES ("Villan", 1000000, 4);
INSERT INTO role (title, salary, department_id) VALUES ("Tech Nerd", 75000, 5);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("James", "Bond", 2, 1);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("M", "",1, null);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Q", "",5, 1);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Corinne", "Dufour", 3, NULL);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Octopussy" ,"",3,NULL);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("May", "Day", 3, NULL);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Natalya", "Simonova", 3, NULL);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Paris", "Carver", 3, NULL);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Solange", "Dimitrios", 4, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Mr.", "Big", 4, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Max", "Zorin", 4, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Elektra", "King", 4, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Emilio", "Largo", 4, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Hugo", "Drax", 4, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Alec", "Trevelyan", 4, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Rosa", "Klebb", 4, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Francisco", "Scaramanga", 4, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Le", "Chiffre", 4, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Ernst Stavro", "Blofeld", 4, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Auric", "Goldfinger", 4, 3);